name: Publish npm beta
on:
  push:
    tags:
      - 'v0.**-beta.*'

jobs:
  publish-beta:
    name: Publish new npm beta version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: yarn test
      - run: yarn build
      - run: yarn publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
